export const ActionTypes = {
    SET_ARR_CHARACTERS: "SET_ARR_CHARACTERS",
    LOADER: "LOADER",
    CHARACTERS_TIM: "CHARACTERS_TIM",
    ADD_CHARACTER: "ADD_CHARACTER",
    SORT_CHARACTER: "SORT_CHARACTER",
    ENEMY_CHARACTER: "ENEMY_CHARACTER",
}